### ISSUE TITLE
npm test - 1 Failure on RedHat 7.x, x86_64, npm version 7.4.0

### ISSUE THREAD

**Issue by seth-priya** [codemirror/CodeMirror#4517]
Hi,

npm test (both on master as well as release 5.23.0) is failing with the following error. This issue is seen specifically on Red Hat (tried on versions 7.0 (x86_64) as well as 7.2 and 7.3 ) as of now. All tests pass on Ubuntu 16.04

npm version is 7.4.0 (installed using nvm install stable)

> codemirror@5.23.0 test /home/test/CodeMirror-5.23.0
> node ./test/run.js

core_rtlMovement
assertion failed (moved right)

1 failure

{ Error: Command failed: /home/test/CodeMirror-5.23.0/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs /home/test/CodeMirror-5.23.0/test/phantom_driver.js

    at ChildProcess.exithandler (child_process.js:211:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/home/test/CodeMirror-5.23.0/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs /home/test/CodeMirror-5.23.0/test/phantom_driver.js' }
npm ERR! Test failed.  See above for more details.

Any suggestions on what could be causing this or how to debug this would be of great help. Is there a way to run a specific test case in debug mode?

Please let me know any further details required with respect to the environment.

Thanks!

Priya

**Comment by adrianheine** [comment]
Could you try again with current `master`? If it still fails, can you give me the output of `npm ls`?

**Comment by seth-priya** [comment]
Thanks for your response @adrianheine 
I am actually now seeing 2 failures with the current master (it was previously 1 failure for the master as well)

This is what I get
> codemirror@5.23.0 test /home/jenkins/codemirror
> node ./test/run.js

core_rtlMovement
assertion failed (moved right)
core_move_bidi_Ö              ÒÑÚ³ Ó§
assertion failed (In step 2, cursor didn't move right)

2 failures

{ Error: Command failed: /usr/bin/phantomjs /home/jenkins/codemirror/test/phantom_driver.js

npm ls is as follows

codemirror@5.23.0 /home/jenkins/codemirror
+-- blint@0.5.1
| +-- acorn@2.7.0
| `-- nomnom@1.8.1
|   +-- chalk@0.4.0
|   | +-- ansi-styles@1.0.0
|   | +-- has-color@0.1.7
|   | `-- strip-ansi@0.1.1
|   `-- underscore@1.6.0
+-- node-static@0.6.0
+-- phantomjs-prebuilt@2.1.14
| +-- es6-promise@4.0.5
| +-- extract-zip@1.5.0
| | +-- concat-stream@1.5.0
| | | +-- inherits@2.0.3
| | | +-- readable-stream@2.0.6
| | | | +-- core-util-is@1.0.2
| | | | +-- isarray@1.0.0
| | | | +-- process-nextick-args@1.0.7
| | | | +-- string_decoder@0.10.31
| | | | `-- util-deprecate@1.0.2
| | | `-- typedarray@0.0.6
| | +-- debug@0.7.4
| | +-- mkdirp@0.5.0
| | | `-- minimist@0.0.8
| | `-- yauzl@2.4.1
| |   `-- fd-slicer@1.0.1
| |     `-- pend@1.2.0
| +-- fs-extra@1.0.0
| | +-- graceful-fs@4.1.11
| | +-- jsonfile@2.4.0
| | `-- klaw@1.3.1
| +-- hasha@2.2.0
| | +-- is-stream@1.1.0
| | `-- pinkie-promise@2.0.1
| |   `-- pinkie@2.0.4
| +-- kew@0.7.0
| +-- progress@1.1.8
| +-- request@2.79.0
| | +-- aws-sign2@0.6.0
| | +-- aws4@1.5.0
| | +-- caseless@0.11.0
| | +-- combined-stream@1.0.5
| | | `-- delayed-stream@1.0.0
| | +-- extend@3.0.0
| | +-- forever-agent@0.6.1
| | +-- form-data@2.1.2
| | | `-- asynckit@0.4.0
| | +-- har-validator@2.0.6
| | | +-- chalk@1.1.3
| | | | +-- ansi-styles@2.2.1
| | | | `-- strip-ansi@3.0.1
| | | +-- commander@2.9.0
| | | | `-- graceful-readlink@1.0.1
| | | `-- is-my-json-valid@2.15.0
| | |   +-- generate-function@2.0.0
| | |   +-- generate-object-property@1.2.0
| | |   | `-- is-property@1.0.2
| | |   +-- jsonpointer@4.0.1
| | |   `-- xtend@4.0.1
| | +-- hawk@3.1.3
| | | +-- boom@2.10.1
| | | +-- cryptiles@2.0.5
| | | +-- hoek@2.16.3
| | | `-- sntp@1.0.9
| | +-- http-signature@1.1.1
| | | +-- assert-plus@0.2.0
| | | +-- jsprim@1.3.1
| | | | +-- extsprintf@1.0.2
| | | | +-- json-schema@0.2.3
| | | | `-- verror@1.3.6
| | | `-- sshpk@1.10.2
| | |   +-- asn1@0.2.3
| | |   +-- assert-plus@1.0.0
| | |   +-- bcrypt-pbkdf@1.0.1
| | |   +-- dashdash@1.14.1
| | |   | `-- assert-plus@1.0.0
| | |   +-- ecc-jsbn@0.1.1
| | |   +-- getpass@0.1.6
| | |   | `-- assert-plus@1.0.0
| | |   +-- jodid25519@1.0.2
| | |   +-- jsbn@0.1.0
| | |   `-- tweetnacl@0.14.5
| | +-- is-typedarray@1.0.0
| | +-- isstream@0.1.2
| | +-- json-stringify-safe@5.0.1
| | +-- mime-types@2.1.14
| | | `-- mime-db@1.26.0
| | +-- oauth-sign@0.8.2
| | +-- qs@6.3.0
| | +-- stringstream@0.0.5
| | +-- tough-cookie@2.3.2
| | | `-- punycode@1.4.1
| | +-- tunnel-agent@0.4.3
| | `-- uuid@3.0.1
| +-- request-progress@2.0.1
| | `-- throttleit@1.0.0
| `-- which@1.2.12
|   `-- isexe@1.1.2
+-- rollup@0.34.13
| `-- source-map-support@0.4.11
|   `-- source-map@0.5.6
+-- rollup-plugin-buble@0.15.0
| +-- buble@0.15.2
| | +-- acorn@3.3.0
| | +-- acorn-jsx@3.0.1
| | | `-- acorn@3.3.0
| | +-- acorn-object-spread@1.0.0
| | | `-- acorn@3.3.0
| | +-- chalk@1.1.3
| | | +-- ansi-styles@2.2.1
| | | +-- escape-string-regexp@1.0.5
| | | +-- has-ansi@2.0.0
| | | +-- strip-ansi@3.0.1
| | | | `-- ansi-regex@2.1.1
| | | `-- supports-color@2.0.0
| | +-- magic-string@0.14.0
| | | `-- vlq@0.2.1
| | +-- minimist@1.2.0
| | `-- os-homedir@1.0.2
| `-- rollup-pluginutils@1.5.2
|   +-- estree-walker@0.2.1
|   `-- minimatch@3.0.3
|     `-- brace-expansion@1.1.6
|       +-- balanced-match@0.4.2
|       `-- concat-map@0.0.1
`-- rollup-watch@2.5.0
  `-- semver@5.3.0

Please let me know if you need any additional information. Thanks!

Priya

**Comment by adrianheine** [comment]
@marijnh Do you know why PhantomJS yields so widely different results on different systems? I don't get any failures with the same version, and while working on the `stickyCursor` branch, travisci's PhantomJS used to produce a lot of test errors I didn't see locally.

**Comment by marijnh** [comment]
It might be linking different versions of whichever unicode library it depends on. Other than that, I have no idea.

**Comment by aj1988aj** [comment]
Aj
