### ISSUE TITLE
cannot compress , ERROR

### ISSUE THREAD

**Issue by tablatronix** [codemirror/CodeMirror#5128]
Anyone have ideas about this ? I am not node literate, just trying to compress my install.

```
\node_modules\uglify-js\
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\USER\AppData\Roaming\npm\node_modules\uglify-js\ ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:678:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

```

**Comment by marijnh** [comment]
Doesn't ring a bell. I'd say a crash in uglify-js is best reported to that project.
