### ISSUE TITLE
codemirror.js:1653 Uncaught TypeError: Cannot read properties of undefined (reading 'height')

### ISSUE THREAD

**Issue by zhangweihong** [codemirror/CodeMirror#6895]
After using setValue ('') in vue3, an error will be reported when entering:

codemirror.js:1653 Uncaught TypeError: Cannot read properties of undefined (reading 'height')
    at lineLength (codemirror.js:1653:14)
    at codemirror.js:5492:19
    at LeafChunk.iterN (codemirror.js:5656:15)
    at Doc.iterN (codemirror.js:5758:21)
    at Doc.iter (codemirror.js:6144:22)
    at makeChangeSingleDocInEditor (codemirror.js:5491:11)
    at makeChangeSingleDoc (codemirror.js:5461:19)
    at makeChangeInner (codemirror.js:5330:5)
    at makeChange (codemirror.js:5321:7)
    at applyTextInput (codemirror.js:8184:7)

**Comment by marijnh** [comment]
Don't put the CodeMirror instance in the vue state. Vue does weird things to objects in its state, which breaks this library.

**Comment by zhangweihong** [comment]
It seems that this problem only appears in the definecomponent function. I have solved this problem by using hook to operate codemirror
